version: '3'

services:
  api:
    build:
      context: ./nika-api
      dockerfile: Dockerfile
    volumes:
      - ./nika-api:/app
      - ./nikac/main:/app/main
    working_dir: /app
    ports:
      - 8000:8000
    command: fastapi dev --host=0.0.0.0
    # depends_on:
    #   - nikac

  ui:
    build:
      context: ./nika-online-editor
      dockerfile: Dockerfile
    volumes:
      - ./nika-online-editor:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start

  # nikac:
  #   build:
  #     context: ./nikac
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nikac:/app
  #   working_dir: /app
  #   command: ./your_c_binary
